### ISSUE TITLE
Review 15/05/2024

### ISSUE THREAD

**Issue by xXcarlos117Xx2** [4GeeksAcademy/Alimilan88-IGPost1#1]
En general esta bien estructurado aunque ocupa toda la pantalla. Te dejo algunos tips para que lo edites si quieres:
- Solo necesitas hacer 1 post, no necesitas hacer 3
- Utiliza `.classes`. Son reutilizables, los `#id` no. Esto significa que no necesitas repetir cosas como:
```css
#postImg2 {
    display: flex;
    object-fit: cover;
    height: 1080px;
    width: 1080px;
    margin: 10px auto;
}

#postImg3 {
    display: flex;
    object-fit: cover;
    height: 1080px;
    width: 1080px;
    margin: 10px auto;
}
```
Si no que puedes asignarle una clase y ya.
`<img src="https://viajes.nationalgeographic.com.es/medio/2017/02/09/qpx-152378209_cbb96df3.jpg" id="postImg4" alt=""></img>`
Cambiarlo a
`<img src="https://viajes.nationalgeographic.com.es/medio/2017/02/09/qpx-152378209_cbb96df3.jpg" class="postImg" alt=""></img>`

y en el css cambiar
```css
#postImg {
    display: flex;
    object-fit: cover;
    height: 1080px;
    width: 1080px;
    margin: 10px auto;
}
```
por
```css
.postImg {
    display: flex;
    object-fit: cover;
    height: 1080px;
    width: 1080px;
    margin: 10px auto;
}
```
y así con todos los `#id`, es mas cómodo y reutilizas código.
- Para arreglar el problema con los tamaños te sugiero que investigues acerca de los tamaños de los contenedores, puedes asignarle un tamaño máximo y mínimo para, aun haciéndolo responsive, se conserve un tamaño mínimo para seguir siendo legible.
Cosas como [max-width](https://www.w3schools.com/cssref/pr_dim_max-width.php), [max-height](https://www.w3schools.com/cssref/pr_dim_max-height.php), [min-width](https://www.w3schools.com/cssref/pr_dim_min-width.php) y [min-height](https://www.w3schools.com/cssref/pr_dim_min-height.php) te podrían ayudar.

### Pero esta bien!, buen trabajo y sigue así! 
@Alimilan88
